const allWords = [
  { en: "about", he: "על" },
  { en: "above", he: "מעל" },
  { en: "across", he: "לרוחב" },
  { en: "action", he: "פעולה" },
  { en: "address", he: "כתובת" },
  { en: "afraid", he: "מפחד" },
  { en: "after", he: "אחרי" },
  { en: "afternoon", he: "אחר הצהריים" },
  { en: "again", he: "שוב" },
  { en: "age", he: "גיל" },
  { en: "ago", he: "לפני" },
  { en: "agree", he: "להסכים" },
  { en: "all", he: "הכל" },
  { en: "not at all", he: "בכלל לא" },
  { en: "almost", he: "כמעט" },
  { en: "alone", he: "לבד" },
  { en: "alphabet", he: "אלפבית" },
  { en: "already", he: "כבר" },
  { en: "also", he: "גם" },
  { en: "always", he: "תמיד" },
  { en: "am", he: "אני" },
  { en: "I'm", he: "אני" },
  { en: "and", he: "ו" },
  { en: "angry", he: "כועס" },
  { en: "animal", he: "חיה" },
  { en: "another", he: "אחר" },
  { en: "answer", he: "תשובה" },
  { en: "any", he: "כלשהו" },
  { en: "anyone", he: "מישהו" },
  { en: "anything", he: "משהו" },
  { en: "appear", he: "להופיע" },
  { en: "April", he: "אפריל" },
  { en: "are", he: "הם" },
  { en: "arrive at", he: "להגיע ל" },
  { en: "ask", he: "לשאול" },
  { en: "ask for", he: "לבקש" },
  { en: "at", he: "ב" },
  { en: "at home", he: "בבית" },
  { en: "August", he: "אוגוסט" },
  { en: "autumn", he: "סתיו" },
  { en: "away", he: "הרחק" },
  { en: "back", he: "חזרה" },
  { en: "bad", he: "רע" },
  { en: "bag", he: "תיק" },
  { en: "baby", he: "תינוק" },
  { en: "be", he: "להיות" },
  { en: "beautiful", he: "יפה" },
  { en: "because", he: "כי" },
  { en: "because of", he: "בגלל" },
  { en: "bed", he: "מיטה" },
  { en: "before", he: "לפני" },
  { en: "begin", he: "להתחיל" },
  { en: "behind", he: "מאחורי" },
  { en: "believe", he: "להאמין" },
  { en: "beside", he: "ליד" },
  { en: "best", he: "הטוב ביותר" },
  { en: "better", he: "טוב יותר" },
  { en: "between", he: "בין" },
  { en: "big", he: "גדול" },
  { en: "birthday", he: "יום הולדת" },
  { en: "a bit of", he: "מעט מ" },
  { en: "blue", he: "כחול" },
  { en: "board", he: "לוח" },
  { en: "body", he: "גוף" },
  { en: "book", he: "ספר" },
  { en: "bored", he: "משעמם" },
  { en: "boring", he: "משעמם" },
  { en: "bottle", he: "בקבוק" },
  { en: "box", he: "קופסה" },
  { en: "boy", he: "ילד" },
  { en: "bread", he: "לחם" },
  { en: "break", he: "לשבור" },
  { en: "breakfast", he: "ארוחת בוקר" },
  { en: "bring", he: "להביא" },
  { en: "brother", he: "אח" },
  { en: "brown", he: "חום (צבע)" },
  { en: "build", he: "לבנות" },
  { en: "bus", he: "אוטובוס" },
  { en: "busy", he: "עסוק" },
  { en: "but", he: "אבל" },
  { en: "buy", he: "לקנות" },
  { en: "by", he: "על ידי" },
  { en: "call", he: "לטלפון/ לקרוא" },
  { en: "can", he: "יכול" },
  { en: "capital", he: "עיר בירה" },
  { en: "car", he: "מכונית" },
  { en: "Take care", he: "לטפל / לדאוג" },
  { en: "careful", he: "זהיר" },
  { en: "Be careful", he: "תיזהר" },
  { en: "cat", he: "חתול" },
  { en: "catch", he: "לתפוס" },
  { en: "center", he: "מרכז" },
  { en: "chair", he: "כיסא" },
  { en: "change", he: "לשנות" },
  { en: "cheap", he: "זול" },
  { en: "children", he: "ילדים" },
  { en: "chocolate", he: "שוקולד" },
  { en: "class", he: "כיתה" },
  { en: "classroom", he: "חדר הכיתה" },
  { en: "clean", he: "נקי" },
  { en: "clear", he: "ברור" },
  { en: "close", he: "קרוב" },
  { en: "closed", he: "סגור" },
  { en: "coffee", he: "קפה" },
  { en: "cold", he: "קר" },
  { en: "color", he: "צבע" },
  { en: "come", he: "לבוא" },
  { en: "come back", he: "תחזור" },
  { en: "computer", he: "מחשב" },
  { en: "cool", he: "קר" },
  { en: "copy", he: "העתק" },
  { en: "cost", he: "עלות" },
  { en: "count", he: "לספור" },
  { en: "country", he: "מדינה" },
  { en: "of course", he: "בוודאי" },
  { en: "cross the road", he: "לחצות את הכביש" },
  { en: "cry", he: "לבכות" },
  { en: "cut", he: "לחתוך" },
  { en: "dad", he: "אבא" },
  { en: "dark", he: "חושך" },
  { en: "date", he: "תאריך" },
  { en: "daughter", he: "בת" },
  { en: "day", he: "יום" },
  { en: "Dear", he: "יקירי" },
  { en: "December", he: "דצמבר" },
  { en: "decide", he: "להחליט" },
  { en: "dictionary", he: "מילון" },
  { en: "different", he: "שונה" },
  { en: "difficult", he: "מסובך" },
  { en: "doctor", he: "דוקטור" },
  { en: "do", he: "לעשות" },
  { en: "dog", he: "כלב" },
  { en: "don't", he: "לא לעשות" },
  { en: "door", he: "דלת" },
  { en: "down", he: "למטה" },
  { en: "draw", he: "לצייר" },
  { en: "dress", he: "שמלה / להתלבש" },
  { en: "drink", he: "לשתות" },
  { en: "drive", he: "לנהוג" },
  { en: "dry", he: "לייבש" },
  { en: "each", he: "כל" },
  { en: "early", he: "מוקדם" },
  { en: "ears", he: "אוזניים" },
  { en: "easy", he: "קַל" },
  { en: "eat", he: "לאכול" },
  { en: "eighteen", he: "שְׁמוֹנֶה עֶשְׂרֵה" },
  { en: "eighty", he: "שְׁמוֹנִים" },
  { en: "eleven", he: "אַחַד עָשָׂר" },
  { en: "email", he: "אימייל" },
  { en: "the end", he: "בְּסוֹף" },
  { en: "in the end", he: "בְּסוֹף" },
  { en: "English", he: "אַנגְלִית" },
  { en: "enjoy", he: "ליהנות" },
  { en: "enough", he: "מַסְפִּיק" },
  { en: "enter", he: "לְהַכנִיס" },
  { en: "evening", he: "עֶרֶב" },
  { en: "every", he: "כֹּל" },
  { en: "everybody", he: "כּוּלָם" },
  { en: "everyone", he: "כֹּל אֶחָד" },
  { en: "everything", he: "הַכֹּל" },
  { en: "example", he: "דוּגמָה" },
  { en: "for example", he: "לְדוּגמָה" },
  { en: "excuse me", he: "תסלח לי" },
  { en: "exercise", he: "תַרגִיל" },
  { en: "expensive", he: "יָקָר" },
  { en: "extra", he: "תוֹסֶפֶת" },
  { en: "eyes", he: "עיניים" },
  { en: "face", he: "פנים" },
  { en: "in fact", he: "למעשה" },
  { en: "fair", he: "הוגן" },
  { en: "fall", he: "סתָיו" },
  { en: "family", he: "משפחה" },
  { en: "far", he: "רחוק" },
  { en: "fast", he: "מָהִיר" },
  { en: "father", he: "אבא" },
  { en: "favorite", he: "מועדף" },
  { en: "February", he: "פֶבּרוּאָר" },
  { en: "feel", he: "להרגיש" },
  { en: "a few", he: "מעטים" },
  { en: "fifteen", he: "חֲמֵשׁ עֶשׂרֵה" },
  { en: "fifth", he: "חֲמִישִׁית" },
  { en: "fifty", he: "חֲמִישִׁים" },
  { en: "film", he: "סֶרֶט" },
  { en: "find", he: "לִמצוֹא" },
  { en: "find out", he: "לְגַלוֹת" },
  { en: "fine", he: "עָדִין" },
  { en: "a fine day", he: "יום טוב" },
  { en: "finish", he: "סִיוּם" },
  { en: "fire", he: "אֵשׁ" },
  { en: "first", he: "רֵאשִׁית" },
  { en: "five", he: "חָמֵשׁ" },
  { en: "flower", he: "פֶּרַח" },
  { en: "fly", he: "לָטוּס" },
  { en: "food", he: "אוכל" },
  { en: "foot", he: "רֶגֶל" },
  { en: "feet", he: "רגליים" },
  { en: "for", he: "עֲבוּר" },
  { en: "forget", he: "לִשְׁכּוֹחַ" },
  { en: "four", he: "ארבע" },
  { en: "fourteen", he: "אַרְבַּע עֶשְׂרֵה" },
  { en: "fourth", he: "רְבִיעִית" },
  { en: "forty", he: "אַרבָּעִים" },
  { en: "free", he: "לְשַׁחְרֵר" },
  { en: "Friday", he: "יוֹם שִׁישִׁי" },
  { en: "friend", he: "חבר" },
  { en: "from", he: "מ-" },
  { en: "in front of", he: "מוּל" },
  { en: "full", he: "מָלֵא" },
  { en: "funny", he: "מַצחִיק" },
  { en: "game", he: "משחק" },
  { en: "garden", he: "גינה" },
  { en: "get", he: "לְקַבֵּל" },
  { en: "girl", he: "יַלדָה" },
  { en: "give", he: "לָתֵת" },
  { en: "glad", he: "שַׂמֵחַ" },
  { en: "glass", he: "זְכוּכִית" },
  { en: "go", he: "לָלֶכֶת" },
  { en: "go on", he: "להמשיך" },
  { en: "going to", he: "עוֹמֵד" },
  { en: "good", he: "טוֹב" },
  { en: "good at", he: "טוב ב" },
  { en: "goodbye", he: "להתראות" },
  { en: "grade", he: "צִיוּן" },
  { en: "great", he: "גָדוֹל" },
  { en: "green", he: "יָרוֹק" },
  { en: "grow", he: "לִגדוֹל" },
  { en: "guess", he: "לְנַחֵשׁ" },
  { en: "hair", he: "שֵׂעַר" },
  { en: "half", he: "חֲצִי" },
  { en: "half past", he: "וחצי" },
  { en: "hand", he: "יד" },
  { en: "hang", he: "לִתְלוֹת" },
  { en: "happen", he: "לִקְרוֹת" },
  { en: "happy", he: "שַׂמֵחַ" },
  { en: "hard", he: "קָשֶׁה" },
  { en: "hat", he: "כּוֹבַע" },
  { en: "have", he: "יש" },
  { en: "have to", he: "מוּכְרָח" },
  { en: "he", he: "הוּא" },
  { en: "head", he: "ראש" },
  { en: "hear", he: "לשמוע" },
  { en: "hello", he: "שלום" },
  { en: "help", he: "לעזור" },
  { en: "her", he: "שֶׁלָה" },
  { en: "herself", he: "עַצמָה" },
  { en: "here", he: "כָּאן" },
  { en: "high", he: "גָבוֹהַ" },
  { en: "him", he: "אוֹתוֹ" },
  { en: "himself", he: "עַצמוֹ" },
  { en: "his", he: "שֶׁלוֹ" },
  { en: "hold", he: "לְהַחזִיק" },
  { en: "home", he: "בַּיִת" },
  { en: "hope", he: "לְקַווֹת" },
  { en: "hot", he: "חַם" },
  { en: "hour", he: "שָׁעָה" },
  { en: "house", he: "בַּיִת" },
  { en: "how", he: "אֵיך" },
  { en: "How are you", he: "מה שלומך" },
  { en: "hundred", he: "מֵאָה" },
  { en: "hungry", he: "רָעֵב" },
  { en: "idea", he: "רַעְיוֹן" },
  { en: "if", he: "אִם" },
  { en: "immediately", he: "מִיָד" },
  { en: "important", he: "חָשׁוּב" },
  { en: "impossible", he: "בִּלתִי אֶפשָׂרִי" },
  { en: "in", he: "ב" },
  { en: "inside", he: "בְּתוֹך" },
  { en: "interested in", he: "מתעניין" },
  { en: "interesting", he: "מעניין" },
  { en: "into", he: "לְתוֹך" },
  { en: "invite", he: "לְהַזמִין" },
  { en: "is", he: "הוא" },
  { en: "it", he: "זֶה" },
  { en: "its", he: "שֶׁלָה" },
  { en: "itself", he: "עצמו" },
  { en: "January", he: "יָנוּאָר" },
  { en: "job", he: "מִשׂרָה" },
  { en: "June", he: "יוּנִי" },
  { en: "July", he: "יוּלִי" },
  { en: "just", he: "רַק" },
  { en: "keep", he: "לִשְׁמוֹר" },
  { en: "kid", he: "יֶלֶד" },
  { en: "kind", he: "סוּג" },
  { en: "kind of", he: "מֵעֵין" },
  { en: "know", he: "לָדַעַת" },
  { en: "large", he: "גָדוֹל" },
  { en: "last", he: "אַחֲרוֹן" },
  { en: "last night", he: "אֶמֶשׁ" },
  { en: "late", he: "מְאוּחָר" },
  { en: "learn", he: "לִלמוֹד" },
  { en: "at least", he: "לְפָחוֹת" },
  { en: "leave", he: "לַעֲזוֹב" },
  { en: "left", he: "שְׁמֹאל" },
  { en: "less", he: "פָּחוֹת" },
  { en: "lesson", he: "לֶקַח" },
  { en: "let's", he: "בואו" },
  { en: "letter", he: "מִכְתָב" },
  { en: "lie", he: "שֶׁקֶר" },
  { en: "lie down", he: "לִשְׁכַּב" },
  { en: "life", he: "חיים" },
  { en: "light", he: "אור" },
  { en: "like", he: "לאהוב" },
  { en: "listen", he: "לְהַקְשִׁיב" },
  { en: "little", he: "קְצָת" },
  { en: "live", he: "לִחיוֹת" },
  { en: "long", he: "אָרוֹך" },
  { en: "look at", he: "להסתכל על" },
  { en: "lost", he: "אָבֵד" },
  { en: "a lot of", he: "הַרבֵּה" },
  { en: "lots of", he: "הַרבֵּה" },
  { en: "love", he: "אַהֲבָה" },
  { en: "lunch", he: "אֲרוּחַת צָהֳרִים" },
  { en: "make", he: "לַעֲשׂוֹת" },
  { en: "man", he: "אָדָם" },
  { en: "men", he: "אֲנָשִׁים" },
  { en: "many", he: "רַבִּים" },
  { en: "how many", he: "כַמָה" },
  { en: "March", he: "מַרס" },
  { en: "it doesn't matter", he: "זה לא משנה" },
  { en: "What's the matter", he: "מה העניין" },
  { en: "May", he: "מַאִי" },
  { en: "maybe", he: "אוּלַי" },
  { en: "me", he: "לִי" },
  { en: "mean", he: "מְמוּצָע" },
  { en: "I mean", he: "כלומר" },
  { en: "What do you mean", he: "למה אתה מתכוון" },
  { en: "meaning", he: "מַשְׁמָעוּת" },
  { en: "meet", he: "לִפְגוֹשׁ" },
  { en: "meeting", he: "פְּגִישָׁה" },
  { en: "memory", he: "זֵכֶר" },
  { en: "message", he: "הוֹדָעָה" },
  { en: "middle", he: "אֶמצַע" },
  { en: "milk", he: "חָלָב" },
  { en: "Do you mind", he: "אכפת לך" },
  { en: "minus", he: "מִינוּס" },
  { en: "minute", he: "דַקָה" },
  { en: "in a minute", he: "תוך דקה" },
  { en: "mistake", he: "טָעוּת" },
  { en: "mix", he: "לְעַרְבֵּב" },
  { en: "mom", he: "אִמָא" },
  { en: "mum", he: "אמא" },
  { en: "at the moment", he: "כרגע" },
  { en: "Monday", he: "יוֹם שֵׁנִי" },
  { en: "money", he: "כֶּסֶף" },
  { en: "month", he: "חוֹדֶשׁ" },
  { en: "moon", he: "יָרֵחַ" },
  { en: "more", he: "יוֹתֵר" },
  { en: "morning", he: "שַׁחַר" },
  { en: "most", he: "רוֹב" },
  { en: "mother", he: "אִמָא" },
  { en: "mouth", he: "פֶּה" },
  { en: "move", he: "מַהֲלָך" },
  { en: "movie", he: "סֶרֶט" },
  { en: "Mr.", he: "מַר" },
  { en: "Mrs.", he: "גְבֶרֶת" },
  { en: "Ms.", he: "גְבֶרֶת" },
  { en: "much", he: "הַרבֵּה" },
  { en: "How much", he: "כַמָה" },
  { en: "music", he: "מוּסִיקָה" },
  { en: "my", he: "שֶׁלִי" },
  { en: "myself", he: "עַצמִי" },
  { en: "name", he: "שֵׁם" },
  { en: "What’s your name", he: "מה שמך" },
  { en: "My name is", he: "שמי הוא" },
  { en: "near", he: "לְיַד" },
  { en: "need", he: "צוֹרֶך" },
  { en: "neighbor", he: "שָׁכֵן" },
  { en: "never", he: "לְעוֹלָם לֹא" },
  { en: "new", he: "חָדָשׁ" },
  { en: "news", he: "חֲדָשׁוֹת" },
  { en: "next", he: "הַבָּא" },
  { en: "next to", he: "לְיַד" },
  { en: "nice", he: "נֶחְמָד" },
  { en: "night", he: "לַיְלָה" },
  { en: "at night", he: "בלילה" },
  { en: "nine", he: "תֵשַׁע" },
  { en: "nineteen", he: "תֵשַׁע עֶשׂרֵה" },
  { en: "ninety", he: "תִשׁעִים" },
  { en: "no", he: "לֹא" },
  { en: "nobody", he: "אַף אֶחָד" },
  { en: "no-one", he: "אף אחד" },
  { en: "not", he: "לֹא" },
  { en: "notebook", he: "מַחבֶּרֶת" },
  { en: "nothing", he: "שׁוּם דָבָר" },
  { en: "November", he: "נוֹבֶמבֶּר" },
  { en: "now", he: "עַכשָׁיו" },
  { en: "number", he: "מִספָּר" },
  { en: "October", he: "אוֹקְטוֹבֶּר" },
  { en: "of", he: "שֶׁל" },
  { en: "often", he: "לְעִתִים קְרוֹבוֹת" },
  { en: "OK", he: "בְּסֵדֶר" },
  { en: "okay", he: "בְּסֵדֶר" },
  { en: "old", he: "יָשָׁן" },
  { en: "How old are you", he: "בן כמה אתה" },
  { en: "I'm … years old", he: "אני בן … שנים" },
  { en: "on", he: "עַל" },
  { en: "once", he: "פַּעַם" },
  { en: "once upon a time", he: "הָיה הָיָה" },
  { en: "one", he: "אֶחָד" },
  { en: "only", he: "רַק" },
  { en: "open", he: "לִפְתוֹחַ" },
  { en: "or", he: "אוֹ" },
  { en: "other", he: "אַחֵר" },
  { en: "our", he: "שֶׁלָנוּ" },
  { en: "ourselves", he: "בְּעָצמֵנוּ" },
  { en: "out", he: "הַחוּצָה" },
  { en: "over", he: "מֵעַל" },
  { en: "own", he: "שֶׁלוֹ" },
  { en: "parents", he: "הוֹרִים" },
  { en: "page", he: "עַמוּד" },
  { en: "paper", he: "נְיָר" },
  { en: "part", he: "חֵלֶק" },
  { en: "past", he: "עָבָר" },
  { en: "pay", he: "לְשַׁלֵם" },
  { en: "pen", he: "עֵט" },
  { en: "pencil", he: "עִפָּרוֹן" },
  { en: "people", he: "אֲנָשִׁים" },
  { en: "perhaps", he: "אוּלַי" },
  { en: "person", he: "אָדָם" },
  { en: "pick up", he: "לֶאֱסוֹף" },
  { en: "picture", he: "תְמוּנָה" },
  { en: "piece of", he: "חתיכה של" },
  { en: "place", he: "מָקוֹם" },
  { en: "plan", he: "לְתַכְנֵן" },
  { en: "play", he: "לְשַׂחֵק" },
  { en: "play a game", he: "לשחק משחק" },
  { en: "please", he: "אָנָא" },
  { en: "poor", he: "יָרוּד" },
  { en: "possible", he: "אֶפשָׁרִי" },
  { en: "practice", he: "לְתַרְגֵל" },
  { en: "problem", he: "בְּעָיָה" },
  { en: "no problem", he: "אֵין בְּעָיָוֹת" },
  { en: "project", he: "פּרוֹיֶקט" },
  { en: "pupil", he: "תַלמִיד" },
  { en: "push", he: "לִדחוֹף" },
  { en: "put", he: "לָשִׂים" },
  { en: "question", he: "שְׁאֵלָה" },
  { en: "quick", he: "מָהִיר" },
  { en: "quiet", he: "שֶׁקֶט" },
  { en: "Be quiet", he: "תהיה בשקט" },
  { en: "radio", he: "רָדִיוֹ" },
  { en: "read", he: "לִקְרוֹא" },
  { en: "ready", he: "מוּכָן" },
  { en: "Are you ready", he: "האם אתה מוכן" },
  { en: "I'm ready", he: "אני מוכן" },
  { en: "real", he: "רִיאָל" },
  { en: "really", he: "בֶּאֱמֶת" },
  { en: "red", he: "אָדוֹם" },
  { en: "remember", he: "לִזכּוֹר" },
  { en: "rest", he: "לָנוּחַ" },
  { en: "return", he: "לַחֲזוֹר" },
  { en: "rich", he: "עָשִׁיר" },
  { en: "right", he: "יָמִינָה" },
  { en: "right now", he: "כרגע" },
  { en: "all right", he: "בְּסֵדֶר" },
  { en: "alright", he: "בְּסֵדֶר" },
  { en: "road", he: "כְּבִישׁ" },
  { en: "room", he: "חֶדֶר" },
  { en: "round", he: "עִגוּל" },
  { en: "rule", he: "כְּלָל" },
  { en: "run", he: "לָרוּץ" },
  { en: "sad", he: "עָצוּב" },
  { en: "the same as", he: "אותו דבר כמו" },
  { en: "Saturday", he: "שַׁבָּת" },
  { en: "say", he: "לוֹמַר" },
  { en: "school", he: "בֵּית סֵפֶר" },
  { en: "second", he: "שְׁנִיָה" },
  { en: "see", he: "לִרְאוֹת" },
  { en: "send", he: "לִשְׁלוֹחַ" },
  { en: "sentence", he: "מִשׁפָּט" },
  { en: "September", he: "סֶפּטֶמבֶּר" },
  { en: "seven", he: "שבע" },
  { en: "seventeen", he: "שְׁבַע עֶשׂרֵה" },
  { en: "seventy", he: "שִׁבעִים" },
  { en: "she", he: "הִיא" },
  { en: "short", he: "קָצָר" },
  { en: "shout", he: "לִצְעוֹק" },
  { en: "show", he: "לְהַצִיג" },
  { en: "shut", he: "לִסְגוֹר" },
  { en: "sick", he: "חוֹלֶה" },
  { en: "side", he: "צַד" },
  { en: "sign", he: "סִימָן" },
  { en: "simple", he: "פָּשׁוּט" },
  { en: "sing", he: "לָשִׁיר" },
  { en: "sister", he: "אָחוֹת" },
  { en: "sit", he: "לָשֶׁבֶת" },
  { en: "six", he: "שֵׁשׁ" },
  { en: "sixteen", he: "שֵׁשׁ עֶשׂרֵה" },
  { en: "sixty", he: "שִׁשִׁים" },
  { en: "size", he: "גוֹדֶל" },
  { en: "What size", he: "איזה גודל" },
  { en: "sky", he: "שָׁמַיִם" },
  { en: "sleep", he: "לִישׁוֹן" },
  { en: "special", he: "מְיוּחָד" },
  { en: "spring", he: "אָבִיב" },
  { en: "summer", he: "קַיִץ" },
  { en: "slow", he: "לְהַאֵט" },
  { en: "small", he: "קָטָן" },
  { en: "smart", he: "לִכאוֹב" },
  { en: "smile", he: "חִיוּך" },
  { en: "so", he: "כָּך" },
  { en: "some", he: "כַּמָה" },
  { en: "somebody", he: "מִישֶׁהוּ" },
  { en: "something", he: "מַשֶׁהוּ" },
  { en: "sometimes", he: "לִפְעָמִים" },
  { en: "son", he: "בֵּן" },
  { en: "soon", he: "בְּקָרוּב" },
  { en: "song", he: "שִׁיר" },
  { en: "sorry", he: "מִצטַעֵר" },
  { en: "I'm sorry", he: "אני מצטער" },
  { en: "speak", he: "לְדַבֵּר" },
  { en: "spell", he: "לַחַשׁ" },
  { en: "sport", he: "ספּוֹרט" },
  { en: "start", he: "הַתחָלָה" },
  { en: "still", he: "עוֹד" },
  { en: "story", he: "כַּתָבָה" },
  { en: "straight", he: "יָשָׁר" },
  { en: "strong", he: "חָזָק" },
  { en: "student", he: "סטוּדֶנט" },
  { en: "suddenly", he: "פִּתְאוֹם" },
  { en: "sun", he: "שֶׁמֶש" },
  { en: "Sunday", he: "יוֹם רִאשׁוֹן" },
  { en: "supper", he: "אֲרוּחַת עֶרֶב" },
  { en: "sure", he: "בַּטוּחַ" },
  { en: "take", he: "לִיטוֹל" },
  { en: "talk", he: "לְדַבֵּר" },
  { en: "tall", he: "גָבוֹהַ" },
  { en: "tea", he: "תֵה" },
  { en: "teach", he: "לְלַמֵד" },
  { en: "telephone", he: "טֵלֵפוֹן" },
  { en: "television", he: "טֵלֶוִיזִיָה" },
  { en: "tell", he: "לְסַפֵּר" },
  { en: "tell a story", he: "לספר סיפור" },
  { en: "test", he: "מִבְחָן" },
  { en: "than", he: "מֵאֲשֶׁר" },
  { en: "thank you", he: "תודה לך" },
  { en: "thanks", he: "תוֹדָה" },
  { en: "that", he: "זֶה" },
  { en: "the", he: "את" },
  { en: "their", he: "שֶׁלָהֶם" },
  { en: "them", he: "אוֹתָם" },
  { en: "themselves", he: "עַצמָם" },
  { en: "then", he: "אָז" },
  { en: "there", he: "שָׁם" },
  { en: "there is", he: "יֵשׁ" },
  { en: "there are", he: "יֵשׁ" },
  { en: "these", he: "אֵלֶה" },
  { en: "they", he: "הֵם" },
  { en: "thing", he: "דָבָר" },
  { en: "think", he: "לַחשׁוֹב" },
  { en: "third", he: "שְׁלִישִׁי" },
  { en: "thirteen", he: "שְׁלוֹשׁ עֶשׂרֵה" },
  { en: "thirty", he: "שְׁלוֹשִׁים" },
  { en: "this", he: "זֶה" },
  { en: "those", he: "הָהֵן" },
  { en: "three", he: "שְׁלוֹשָׁה" },
  { en: "Thursday", he: "יוֹם חֲמִישִׁי" },
  { en: "time", he: "זְמַן" },
  { en: "What's the time", he: "מה השעה" },
  { en: "The time is", he: "השעה היא" },
  { en: "to", he: "אֶל" },
  { en: "today", he: "הַיוֹם" },
  { en: "together", he: "יַחַד" },
  { en: "tomorrow", he: "מָחָר" },
  { en: "tonight", he: "הַלַילָה" },
  { en: "too", he: "גַם" },
  { en: "too much", he: "יוֹתֵר מִדַי" },
  { en: "town", he: "עִיר" },
  { en: "tree", he: "עֵץ" },
  { en: "go on a trip", he: "לצאת לטיול" },
  { en: "truck", he: "מַשָׂאִית" },
  { en: "true", he: "נָכוֹן" },
  { en: "try", he: "לְנַסוֹת" },
  { en: "Tuesday", he: "יוֹם שְׁלִישִׁי" },
  { en: "turn", he: "פִּנָה" },
  { en: "turn left", he: "לפנות שמאלה" },
  { en: "turn right", he: "לפנות ימינה" },
  { en: "twenty", he: "עֶשְׂרִים" },
  { en: "two", he: "דוּ" },
  { en: "under", he: "תַחַת" },
  { en: "understand", he: "לִהַבִין" },
  { en: "until", he: "עַד" },
  { en: "up", he: "לְמַעלָה" },
  { en: "us", he: "לָנוּ" },
  { en: "use", he: "לְהִשְׁתַמֵשׁ" },
  { en: "usually", he: "בְּדֶרֶך כְּלַל" },
  { en: "vacation", he: "חוּפשָׁה" },
  { en: "very", he: "מְאוֹד" },
  { en: "wait for", he: "לחכות ל" },
  { en: "walk", he: "לָלֶכֶת" },
  { en: "wall", he: "קִיר" },
  { en: "want", he: "מַחְסוֹר" },
  { en: "was", he: "היה" },
  { en: "were", he: "היו" },
  { en: "wash", he: "לִשְׁטוֹף" },
  { en: "watch", he: "לִצְפּוֹת" },
  { en: "water", he: "מַיִם" },
  { en: "way", he: "דֶרֶך" },
  { en: "Which way", he: "באיזו דרך" },
  { en: "we", he: "אָנוּ" },
  { en: "wear", he: "לִלבּוֹשׁ" },
  { en: "Wednesday", he: "יוֹם רְבִיעִי" },
  { en: "week", he: "שָׁבוּעַ" },
  { en: "welcome", he: "קַבָּלַת פָּנִים" },
  { en: "you're welcome", he: "אתה מוזמן" },
  { en: "well", he: "טוֹב" },
  { en: "as well", he: "גַם כֵּן" },
  { en: "as well as", he: "כמו גם" },
  { en: "Well done", he: "כל הכבוד" },
  { en: "What a pity", he: "כמה חבל" },
  { en: "What a shame", he: "איזה בושה" },
  { en: "what", he: "מַה" },
  { en: "when", he: "כַּאֲשֵׁר" },
  { en: "where", he: "אֵיפֹה" },
  { en: "while", he: "בְּעוֹד" },
  { en: "white", he: "לָבָן" },
  { en: "who", he: "WHO" },
  { en: "why", he: "מַדוּעַ" },
  { en: "will", he: "רָצוֹן" },
  { en: "window", he: "חַלוֹן" },
  { en: "winter", he: "חוֹרֶף" },
  { en: "wish", he: "בַּקָשָׁה" },
  { en: "with", he: "עִם" },
  { en: "without", he: "לְלֹא" },
  { en: "woman", he: "אִשָׁה" },
  { en: "women", he: "נָשִׁים" },
  { en: "wonderful", he: "נִפלָא" },
  { en: "word", he: "מִלָה" },
  { en: "work", he: "עֲבוֹדָה" },
  { en: "world", he: "עוֹלָם" },
  { en: "worse", he: "גָרוּעַ יוֹתֵר" },
  { en: "worst", he: "גָרוּעַ בִּיוֹתֵר" },
  { en: "write", he: "לִכתוֹב" },
  { en: "wrong", he: "טָעוּת" },
  { en: "year", he: "שָׁנָה" },
  { en: "yellow", he: "צָהוֹב" },
  { en: "yes", he: "כֵּן" },
  { en: "yesterday", he: "אֶתמוֹל" },
  { en: "you", he: "אַתָה" },
  { en: "young", he: "צָעִיר" },
  { en: "your", he: "שֶׁלְךָ" },
];

export { allWords };